set shell := ["nu", "-c"]

default:
  just --list

run-online input="hello":
  scala-cli run main.scala -- {{input}}

run input="hello":
  scala-cli run --power --offline main.scala -- {{input}}

setup-ide:
  scala-cli setup-ide .

build-native-online:
  scala-cli package --power --force --native . -o dist/main.exe

build-native:
  scala-cli package --power --offline --force --native . -o dist/main.exe

[windows]
install: build-native
  cp dist/main.exe D:/dev-env/bin/icoder-scala.exe

[linux]
install: build-native
  cp dist/main ~/.local/bin/icoder-scala

edit: setup-ide
   idea64 .

re-edit: clean setup-ide
  idea64 .

clean:
  rm -rf .bsp .idea .scala-build
