set shell := ["nu", "-c"]

default:
  just --list

test:
  mill test

sbt_test:
  sbtn test

sbt_compile:
  sbtn compile

run *args:
  mill run {{args}}

build_sbt:
  sbtn 'show graalvm-native-image:packageBin'

alias install := install_sbt

[windows]
install_sbt: build_sbt
  cp target/graalvm-native-image/justfile_convert.exe D:/dev-env/bin/

build_mill:
  mill nativeImage

[windows]
install_mill: build_mill
  cp out/nativeImage.dest/justfile_convert.exe D:/dev-env/bin/


sbt_run *args:
  sbtn run {{args}}

compile:
  mill compile

deps_update:
  scala-update

dist:
  sbtn stage

dev:
  mill --watch run

sbt_dev:
  sbt '~reStart --- -Dfile.encoding=utf-8'

edit_clean:
  rm -rf .bsp .idea

console:
  mill -i console
