[package]
authors = ["itang <live.tang@gmail.com>"]
name = "rtitle"
version = "0.3.1-20220203"
edition = "2021"

[dependencies]
chrono = "0.4.19"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[profile.release]
strip = "debuginfo"
