set shell := ["nu", "-c"]

default:
  just --list

all:
  deno task build:dev ; deno task run

run:
  deno run -A --unstable target/scala-3.5.0-RC2/head_news-fastopt/main.js

build_dev:
  sbt fastLinkJS

compile:
  deno compile -A --unstable target/scala-3.5.0-RC2/head_news-fastopt/main.js

build_prod:
  sbt fullLinkJS

dev:
  sbt '~fastLinkJS' & sleep 8; deno run -A --unstable --watch target/scala-3.5.0-RC2/head_news-fastopt/main.js

install:
  sbt fullLinkJS ; rm dist/*; deno compile -A --unstable -o dist/head_news target/scala-3.5.0-RC2/head_news-opt/main.js; cp dist/head_news.exe D:/dev-env/bin/head_news_scala.exe

