[toolchain]
#channel = "stable"
channel = "nightly"
#channel = "nightly-2026-05-01"

#components = [ "rustfmt", "rustc-dev" ]
#targets = [ "wasm32-unknown-unknown", "thumbv2-none-eabi" ]
#profile = "minimal"
