// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsonRpc from "./JsonRpc.res.mjs";

let ServerInfo = {};

function make(subPath, urlPrefix) {
  return {
    subPath: subPath,
    urlPrefix: urlPrefix
  };
}

async function getServerInfo(self) {
  return await JsonRpc.get(self.urlPrefix + "/" + self.subPath + "/getServerInfo");
}

let Ops = {
  make: make,
  getServerInfo: getServerInfo
};

let Sdk = {};

function make$1(urlPrefix) {
  return {
    urlPrefix: urlPrefix,
    ops: {
      subPath: "ops",
      urlPrefix: urlPrefix
    }
  };
}

export {
  ServerInfo,
  Ops,
  Sdk,
  make$1 as make,
}
/* No side effect */
