// Generated by ReScript, PLEASE EDIT WITH CARE


let RpcResult = {};

async function get_json(url) {
  let resp = await fetch(url);
  return await resp.json();
}

async function get(url) {
  return await get_json(url);
}

export {
  RpcResult,
  get,
}
/* No side effect */
