# justfile

set shell := ["nu", "-c"]

bin_dir := if os_family() == "windows" { "D:/dev-env/bin" } else { env_var('HOME') / 'dev-env' / 'bin' }
bin_name := if os_family() == "windows" { 'en.exe' } else { 'en' }

default:
  just --list

dev:
  mill -w run

run *args='':
  mill run {{args}}

build:
  mill nativeLink

test:
  mill test

install: build
  -{{bin_name}} --version
  cp out/nativeLink.dest/out {{bin_dir}}/{{bin_name}}
  {{bin_name}} --version

info:
  echo 'bin_dir: {{bin_dir}}'
