set shell := ["nu", "-c"]

default:
  just --list

run:
  cargo run

repl:
  @echo "':dep .' for current project repl"
  evcxr

doc:
  cargo doc --document-private-items --open

dev:
  cargo watch -x run

lint:
  cargo clippy --no-deps

edit:
  idea64 .

install:
  cargo install --path . --locked
