set shell := ["nu", "-c"]

default:
  just --list


compile-sbt:
  sbt compile

compile-mill:
  mill compile

alias compile := compile-mill

run-mill:
  mill run diff --left-file . --right-file . -i .git -i .idea -i target

run-sbt:
  sbt run

alias run := run-mill


dev-mill:
  mill --watch run diff -l . -r . -i .git -i .idea -i target

dev-sbt:
  sbt '~reStart --- -Dfile.encoding=utf-8'

alias dev := dev-mill


build-sbt:
  sbt 'show graalvm-native-image:packageBin'

build-mill:
  mill nativeImage

alias build := build-sbt


re-edit-bsp:
  deno task edit:clean ; deno task edit:bsp

dist-sbt:
  sbt stage

alias dist := dist-sbt



[windows]
install-sbt: build-sbt
  cp target/graalvm-native-image/diffdir_scala.exe D:/dev-env/bin/idir.exe

[windows]
install-mill: build-mill
  cp out/nativeImage.dest/diffdir_scala.exe D:/dev-env/bin/idir.exe

target_dir := "D:/dev-env/diffdir_scala"

[windows]
install-jit: dist-sbt
    rm -rf {{target_dir}}
    mkdir {{target_dir}}
    cp -rf target/universal/stage/* {{target_dir}}
    cp {{target_dir}}/bin/diffdir_scala.bat {{target_dir}}/bin/idir.bat

alias install := install-sbt


console:
  mill -i console

fatjar:
  sbt assembly

run-fatjar: fatjar
  java -DSOME_KEY=1 -jar target/scala-3.4.0/diffdir_scala-assembly-0.1.0-SNAPSHOT.jar


test:
  mill test

test-sbt:
  sbt test