set shell := ["nu", "-c"]

default:
  just --list

test:
  mill test

test-sbt:
  sbt test

compile-sbt:
  sbt compile

run:
  mill run diff --left-file D:\downloads\a --right-file D:\downloads\b

dev:
  mill --watch run diff --left-file D:\downloads\a --right-file D:\downloads\b

build:
  sbt 'show graalvm-native-image:packageBin'

[windows]
install: build
  cp target/graalvm-native-image/diffdir_scala.exe D:/dev-env/bin/

build-mill:
  mill nativeImage

idea:
  mill mill.scalalib.GenIdea/idea

run-sbt:
  sbt run

re-edit-bsp:
  deno task edit:clean ; deno task edit:bsp

compile:
  mill compile

deps-update:
  scala-update

reset:
  sbt clean ; sbt shutdownall ; bloop exit

edit:
  deno task idea ; idea64 .

dist:
  sbt stage


[windows]
install-mill: build-mill
  cp out/nativeImage.dest/diffdir_scala.exe D:/dev-env/bin/


target_dir := "D:/dev-env/diffdir_scala"

[windows]
install2: dist
    rm -rf {{target_dir}}
    mkdir {{target_dir}}
    cp -rf target/universal/stage/* {{target_dir}}
    cp {{target_dir}}/bin/diffdir_scala.bat {{target_dir}}/bin/idir.bat


dev-sbt:
  sbt '~reStart --- -Dfile.encoding=utf-8'

edit-clean:
  rm -rf .bsp .idea

re-edit:
  deno task edit:clean ; deno task edit

console:
  mill -i console

fatjar:
  sbt assembly

run-fatjar: fatjar
  java -DSOME_KEY=1 -jar target/scala-3.4.0/diffdir_scala-assembly-0.1.0-SNAPSHOT.jar