set shell := ["nu", "-c"]

default:
  just --list

run:
  cargo run

run-test-url *args="-m qsl https://user1:pass@www.baidu.com/portal?a=1&b=2&c=3&c=4#/apps/main":
  cargo run -- url {{args}}

doc:
  cargo doc --document-private-items --open


dev:
  cargo watch -x run

lint:
  cargo clippy --no-deps

edit:
  idea64 .

install:
  cargo install --force --path .

fmt:
  cargo fmt
