set shell := ["nu", "-c"]

default:
  just --list

run *args="":
  cargo run -- {{args}}

run-test-url *args="-m qsl https://user1:pass@www.baidu.com/portal?a=1&b=2&c=3&c=4#/apps/main":
  cargo run -- url {{args}}

doc:
  cargo doc --document-private-items --open


dev *args="":
  cargo watch -x 'run -- {{args}}'

lint:
  cargo clippy --no-deps

edit:
  idea64 .

install:
  cargo install --force --path .

fmt:
  cargo fmt
