task :default => :build

def nightly_cargo(cmd)
  sh "multirust run nightly cargo #{cmd}"
end

task :build do
  nightly_cargo 'build --release'
  sh 'cp target/release/rtitle ~/dev-env/tools/'
end

task :run do
  nightly_cargo 'run --release'
end

task :test do
  nightly_cargo 'test --release'
end
