urls = [
     "https://twitter.com",
     "http://www.douban.com",
     "http://www.weibo.com",
     #"https://trello.com/b/wv4Jd9e3/simple-todolist",
     "http://bbs.szhome.com/30017.html",
     #"https://www.zhihu.com/column/taowen",
     #"https://www.zhihu.com/people/canonical-entropy/posts",
     #"https://www.zhihu.com/people/tchen/posts",
     #"https://discord.com/channels/@me",
     "http://www.oschina.net/",
     "http://www.infoq.com/cn",
     "https://www.infoq.cn/topic/architecture",
     "https://www.infoq.cn/topic/CloudNative",
     "https://www.infoq.cn/topic/cloud-computing",
     "https://www.infoq.cn/topic/programing-languages",
     "http://36kr.com/",
     "https://news.ycombinator.com/news",
     "https://github.com/stars?direction=desc&sort=updated",
     "https://github.com/trending",
     "https://github.com/trending/typescript?since=daily",
     "https://github.com/trending/python?since=daily",
     "https://github.com/trending/go?since=daily",
     #"https://github.com/trending/java?since=daily",
     #"https://gitter.im/flix/Lobby",
     #"https://github.com/trending/fsharp?since=daily",
     #"https://gitter.im/fable-compiler/Fable",
     #"https://www.zhihu.com/column/fsharp",
     #"https://discuss.lightbend.com/c/akka/5",
     #"https://github.com/trending/scala?since=daily",
     #"https://www.reddit.com/r/scala/",
     #"https://gitter.im/scala/scala",
     #"https://gitter.im/scala-js/scala-js",
     #"https://gitter.im/scala-native/scala-native",
     "https://rustcc.cn/section?id=f4703117-7e6b-4caf-aa22-a3ad3db6898f",
     "https://github.com/trending/rust?since=daily",
     "https://users.rust-lang.org/",
     "https://www.reddit.com/r/rust",
     "https://lobste.rs/",
] #"https://gitter.im/lampepfl/dotty",
