[package]
authors = ["itang <live.tang@gmail.com>"]
name = "rdict"
version = "0.2.1"

[dependencies]
ansi_term = "0.9.0"
reqwest = "0.4.0"
serde = "0.9.7"
serde_derive = "0.9.7"
#serde_json = "0.9.6"
