[package]
authors = ["itang <live.tang@gmail.com>"]
name = "rdict"
version = "0.2.5"

[dependencies]
ansi_term = "0.9.0"
reqwest = "0.6.2"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
structopt = "0.0.5"
structopt-derive = "0.0.5"
