[package]
authors = ["itang <live.tang@gmail.com>"]
name = "rdict"
version = "0.2.7"

[dependencies]
ansi_term = "0.9.0"
reqwest = "0.6.2"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.2"
structopt ="0.2"
structopt-derive = "0.2"
toml = "0.4.2"
