# justfile

set shell := ["nu", "-c"]


default:
  just --list


prepare:
  dotnet tool restore


run *args="":
  dotnet run -- {{args}}

run-no-build *args:
  dotnet run --no-build -- {{args}}


dev *args="":
  dotnet watch run -- {{args}}


[windows]
publish:
  dotnet publish -r win-x64 -c Release --self-contained /p:PublishSingleFile=true /p:PublishTrimmed=true
  @ls -l bin\Release\net8.0\win-x64\publish

[linux]
publish:
  dotnet publish -r linux-x64 -c Release --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true

fmt:
  dotnet fantomas .
