set shell := ["nu", "-c"]

default:
  just --list

prepare:
  dotnet tool restore


compile:
  dotnet fable -o build/js

dev:
  dotnet fable watch . -o build/js/src --run deno run -A --unstable --watch build/js/src/Program.js

run: compile
  deno run -A --unstable build/js/src/Program.js

build: compile
  deno compile -A -o build/bin/jsonfmt-fs build/js/src/Program.js

[windows]
install: build
  cp build/bin/jsonfmt-fs.exe D:/dev-env/bin/

[linux]
install: build
  cp build/bin/jsonfmt-fs ~/.local/bin/


[windows]
publish:
  dotnet publish -r win-x64 -c Release --self-contained /p:PublishSingleFile=true /p:PublishTrimmed=true
  @ls -l bin\Release\net8.0\win-x64\publish

[linux]
publish:
  dotnet publish -r linux-x64 -c Release --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true


[windows]
publish-aot:
  dotnet publish -r win-x64 -c Release
  ls bin\Release\net8.0\win-x64\publish\

[linux]
publish-aot:
  dotnet publish -r linux-x64 -c Release

fmt:
  dotnet fantomas .

clean:
  dotnet fable clean --yes
  dotnet clean
