// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "./Util.res.mjs";
import * as Types from "./Types.res.mjs";
import * as Nodeprocess from "node:process";

function main() {
  let args = Nodeprocess.argv;
  console.log("DEBUG: args=" + args.toString());
  let appArgs = Types.AppArgs.parseArgs(args);
  console.log("INFO: appArgs=", appArgs);
  Types.AppArgs.setDefault(appArgs, "Qsl", "https://www.baidu.com/hello?a=1&b=2&b=3#/main");
  console.log("INFO: after set default, appArgs=", appArgs, "\n");
  let mode = appArgs.mode;
  if (mode !== undefined) {
    appArgs.urls.forEach((url, index) => {
      console.log("[" + (index + 1 | 0).toString() + "]INFO: url=" + url);
      console.log(JSON.stringify(Util.UrlOps.toObj(new URL(url), mode), undefined, 2), "\n");
    });
  } else {
    console.log("ERROR: unknown mode");
  }
}

main();

/*  Not a pure module */
