// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function modeFromString(s) {
  switch (s) {
    case "qs" :
      return "Qs";
    case "qsl" :
      return "Qsl";
    default:
      return;
  }
}

function parseArgs(raw_args) {
  let args = raw_args.slice(2, raw_args.length);
  let ret = {
    mode: "",
    urls: []
  };
  let index = 0;
  while (index < args.length) {
    let curr = Core__Option.getOr(args[index], "");
    if (curr === "--mode" || curr === "-m") {
      ret.mode = Core__Option.getOr(args[index + 1 | 0], "");
      index = index + 1 | 0;
    } else if (curr.startsWith("-")) {
      console.log("WARN: unknown " + curr);
    } else {
      ret.urls.push(curr);
    }
    index = index + 1 | 0;
  };
  return ret;
}

export {
  modeFromString,
  parseArgs,
}
/* No side effect */
